POST http://localhost:8080/api/v1/accounts
Content-Type: application/json

{
  "documentNumber": "12345678940"
}

###

GET http://localhost:8080/api/v1/accounts/1

###

POST http://localhost:8080/api/v1/transactions
Content-Type: application/json

{
  "accountId": 2,
  "operationTypeId": 4,
  "amount": 20.33
}
