DELETE
FROM TRANSACTIONS;
DELETE
FROM ACCOUNTS;
DELETE
FROM OPERATIONS_TYPES;

INSERT INTO OPERATIONS_TYPES (Operation_Type_ID, Description)
VALUES (1, 'COMPRA A VISTA');

INSERT INTO OPERATIONS_TYPES (Operation_Type_ID, Description)
VALUES (2, 'COMPRA PARCELADA');

INSERT INTO OPERATIONS_TYPES (Operation_Type_ID, Description)
VALUES (3, 'SAQUE');

INSERT INTO OPERATIONS_TYPES (Operation_Type_ID, Description)
VALUES (4, 'PAGAMENTO');

INSERT INTO Accounts(Account_ID, Document_Number)
VALUES (1, '12345678900');


